# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\"1\n\x10\x44\x65tectionRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"#\n\x11\x44\x65tectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2O\n\x10\x44\x65tectionService\x12;\n\x10StreamDetections\x12\x11.DetectionRequest\x1a\x12.DetectionResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONREQUEST']._serialized_start=19
  _globals['_DETECTIONREQUEST']._serialized_end=68
  _globals['_DETECTIONRESPONSE']._serialized_start=70
  _globals['_DETECTIONRESPONSE']._serialized_end=105
  _globals['_DETECTIONSERVICE']._serialized_start=107
  _globals['_DETECTIONSERVICE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
